# https://github.com/apps/settings

repository:
  # See https://docs.github.com/ja/rest/repos/repos#update-a-repository

  ####################################
  # General
  ####################################
  description: Memory Lovers repogitory templates
  default_branch: main
  private: false
  is_template: false

  ####################################
  # Feature
  ####################################
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false

  ####################################
  # Pull Requests
  ####################################
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  squash_merge_commit_title: PR_TITLE
  delete_branch_on_merge: true
# Labels: define labels for Issues and Pull Requests
# labels:
