name: one_day_price
packages:
  - app

command:
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
  version:
    branch: main
    releaseUrl: true

scripts:
  bootstrap: flutter pub get

  clean: melos exec -- fvm flutter clean

  format: melos exec -- fvm dart format .

  gen: melos exec -- fvm dart run build_runner build --delete-conflicting-outputs

sdkPath: .fvm/flutter_sdk
