name: one_day_price
packages:
  - app
  - widgetbook

command:
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
  version:
    branch: main
    releaseUrl: true

scripts:
  bootstrap: flutter pub get

  clean: melos exec -- flutter clean

  format: melos exec -- dart format .

  gen: melos exec -- dart run build_runner build --delete-conflicting-outputs

  lint: |
    melos exec -- flutter analyze
    melos exec -- dart run custom_lint

  test: melos exec --scope="*app*" -- flutter test

sdkPath: .fvm/flutter_sdk
