// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGe46i_wnu1t9OfU63sA0NAN-0bF34Wc0',
    appId: '1:272104754808:web:f096e7632915c64bcc278d',
    messagingSenderId: '272104754808',
    projectId: 'memorylovers-myapp-stag',
    authDomain: 'memorylovers-myapp-stag.firebaseapp.com',
    storageBucket: 'memorylovers-myapp-stag.firebasestorage.app',
    measurementId: 'G-HYQ2KYXT5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7aHHiX2GBcp0D1kfZRnl1Ey8qN_onOg',
    appId: '1:272104754808:android:6795356ba7d0508bcc278d',
    messagingSenderId: '272104754808',
    projectId: 'memorylovers-myapp-stag',
    storageBucket: 'memorylovers-myapp-stag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfZmp77sP8ujuiOY2Iwbpn1yHHrBPAtQ',
    appId: '1:272104754808:ios:3f891a356a871a93cc278d',
    messagingSenderId: '272104754808',
    projectId: 'memorylovers-myapp-stag',
    storageBucket: 'memorylovers-myapp-stag.firebasestorage.app',
    iosClientId: '272104754808-eugk96pvgvh22c5f8q8efkpnd2j3lt3c.apps.googleusercontent.com',
    iosBundleId: 'com.memorylovers.myapp.dev',
  );

}