// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stag.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHI-8Swhb2GFtQuuN6E8m7MIEAZ81ZOU',
    appId: '1:764704445887:web:1878c2b659dc39e5827d0a',
    messagingSenderId: '764704445887',
    projectId: 'yattaday-stag',
    authDomain: 'yattaday-stag.firebaseapp.com',
    storageBucket: 'yattaday-stag.firebasestorage.app',
    measurementId: 'G-F0SX70T639',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqBAbIftvbLXi09W5wNXLMXZQf8JW16g',
    appId: '1:764704445887:android:9aa3870da493c796827d0a',
    messagingSenderId: '764704445887',
    projectId: 'yattaday-stag',
    storageBucket: 'yattaday-stag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYmWaGEP-mPhO12Rn-OX2uzZ24B0tR0U',
    appId: '1:764704445887:ios:4156f7c0271e7456827d0a',
    messagingSenderId: '764704445887',
    projectId: 'yattaday-stag',
    storageBucket: 'yattaday-stag.firebasestorage.app',
    iosClientId: '764704445887-mnpo5pat47inm0sm91g4n614f942o874.apps.googleusercontent.com',
    iosBundleId: 'com.memorylovers.yattaday.stag',
  );

}