// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gezIwuywuyb7xeMOoHe1rjuTs06hWcY',
    appId: '1:249468482016:web:ad1420b260d6e491e3fb85',
    messagingSenderId: '249468482016',
    projectId: 'memorylovers-myapp-prod',
    authDomain: 'memorylovers-myapp-prod.firebaseapp.com',
    storageBucket: 'memorylovers-myapp-prod.firebasestorage.app',
    measurementId: 'G-6501NMPX7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtTtLxyMQL3Tf-5xcoES_Hy3HNV9k878',
    appId: '1:249468482016:android:d8e388151596533be3fb85',
    messagingSenderId: '249468482016',
    projectId: 'memorylovers-myapp-prod',
    storageBucket: 'memorylovers-myapp-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GO-qcgUMT6tijfB345Bbli5_HDmyCpo',
    appId: '1:249468482016:ios:72319fc0c6717212e3fb85',
    messagingSenderId: '249468482016',
    projectId: 'memorylovers-myapp-prod',
    storageBucket: 'memorylovers-myapp-prod.firebasestorage.app',
    iosClientId: '249468482016-u49lrnncs6krhhn2cmd97rcbus3t7fll.apps.googleusercontent.com',
    iosBundleId: 'com.memorylovers.myapp',
  );

}