name: common_widget
description: Shared UI components and assets for yattaday apps
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

# https://pub.dev/packages/flutter_gen_runner
flutter_gen:
  output: lib/_gen/
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false
  assets:
    outputs:
      package_parameter_enabled: true
