global_options:
targets:
  $default:
    builders:
      # https://pub.dev/packages/slang
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          translate_var: i18n
          input_directory: assets/i18n
          output_directory: lib/_gen/i18n
          timestamp: false
