name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  quality-checks:
    name: format/lint/test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup FVM and Flutter
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Install Melos
        run: dart pub global activate melos

      - name: ls
        run: ls -al

      - name: Bootstrap workspace
        run: melos bootstrap

      - name: Run code generation
        run: melos run gen --no-select

      - name: Check Dart formatting
        run: melos run format --no-select

      - name: Run lint (analyze + custom_lint)
        run: melos run lint --no-select

      - name: Check Markdown formatting
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

      - name: Run tests
        run: melos run test --no-select

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: app/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
