name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvm/flutter_version
        cache: true
        
    - name: Install Melos
      run: dart pub global activate melos
        
    - name: Bootstrap workspace
      run: melos bootstrap
        
    - name: Run code generation
      run: melos run gen --no-select
        
    - name: Check formatting
      run: melos run format --no-select
        
    - name: Analyze code
      run: melos run lint --no-select
        
    - name: Run tests
      run: melos run test --no-select
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvm/flutter_version
        cache: true
        
    - name: Install Melos
      run: dart pub global activate melos
        
    - name: Bootstrap workspace
      run: melos bootstrap
        
    - name: Run code generation
      run: melos run gen --no-select
        
    - name: Build Android APK
      run: |
        cd app
        fvm flutter build apk --release --flavor prod
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: app/build/app/outputs/flutter-apk/app-prod-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvm/flutter_version
        cache: true
        
    - name: Get dependencies
      run: |
        cd app
        fvm flutter pub get
        
    - name: Run code generation
      run: |
        cd app
        fvm dart run build_runner build --delete-conflicting-outputs
        
    - name: Build iOS app
      run: |
        cd app
        fvm flutter build ios --release --flavor prod --no-codesign
        
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvm/flutter_version
        cache: true
        
    - name: Get dependencies
      run: |
        cd app
        fvm flutter pub get
        
    - name: Run code generation
      run: |
        cd app
        fvm dart run build_runner build --delete-conflicting-outputs
        
    - name: Build Web app
      run: |
        cd app
        fvm flutter build web --release
        
    - name: Upload Web artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: app/build/web/