name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvm/flutter_version
        cache: true
        
    - name: Install Melos
      run: dart pub global activate melos
        
    - name: Bootstrap workspace
      run: melos bootstrap
        
    - name: Run code generation
      run: melos run gen --no-select
        
    - name: Check Dart formatting
      run: melos run format --no-select
        
    - name: Run lint (analyze + custom_lint)
      run: melos run lint --no-select
        
    - name: Check Markdown formatting
      uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        globs: '**/*.md'